my_library/urls.py
from django.contrib import admin
from django.urls import path


from django.conf import settings
from django.conf.urls.static import static

import authentication.views
import blog.views
from blog.models import Blog

from blog.views import blog_search


urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', authentication.views.signup_page, name='signup'),# s'inscrire
    path('login/', authentication.views.login_page, name='login'),# se connecter
    path('logout', authentication.views.logout_user, name='logout'),# se déconnecter

    path('', blog.views.base, name='base' ),
    path('home/', blog.views.home, name='home'),# si ont est connecter
    path('photo/upload/', blog.views.photo_upload, name='photo_upload'),# page pour ajouter une photo de profile
    path('profile-photo/upload', authentication.views.upload_profile_photo,
         name='upload_profile_photo'),# page pour changer photo de profile

    path('profile/', blog.views.view_profile, name='profile'),
    path('remove_comics/<int:comics_id>', authentication.views.remove_comics, name='remove_comics'),
    path('all_profile/', authentication.views.all_profile, name='all_profile'),
    path('view_profile/<int:user_id>', authentication.views.view_profile, name='view_profile'),



    path('blog/create', blog.views.blog_and_photo_upload, name='blog_create'),
    
    # path('blog/multiple_create', blog.views.multiple_create, name='multiple_create'),

    path('blog/<int:comics_id>', blog.views.view_blog, name='view_comics'),

    path('blog/one_shot/', blog.views.one_shot, name='one_shot'),

    path('blog/Posseded/', blog.views.posseded, name='posseded'),
    path('blog/Want/', blog.views.want, name='want'),
    path('blog/series_comics/', blog.views.list_series_comics, name='series_comics'),
    path('blog/rebirth/', blog.views.category_rebirth, name='rebirth'),
    path('blog/New_52/', blog.views.category_52, name='New 52'),
    path('blog/Superman/', blog.views.category_heros, name='Superman'),
    path('blog/Black_Label', blog.views.category_BL, name='BL'),

    
    path('blog/<int:comics_id>/update', blog.views.update, name='update_blog'),

    path('blog/<int:comics_id>/edit', blog.views.delete, name='edit_blog'),
    path('search/', blog.views.blog_search, name='search'),




    path('follow-users/', blog.views.follow_users, name='follow_users'), #formulaire pour suivre un utilisateur

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from PIL import Image
from django.contrib.auth import get_user_model



# Create your models here.


class Photo(models.Model):
    images = models.ImageField(verbose_name='image')
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_ceated = models.DateTimeField(auto_now_add=True)
    IMAGE_MAX_SIZE = (800, 800)

class Blog(models.Model):
    photo = models.ForeignKey(
        Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
contributors = models.ManyToManyField(
settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')

class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)
    
    class Meta:
        unique_together = ('contributor', 'blog')


class Comics(models.Model):
    photo = models.ForeignKey(
        Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    one_shot = models.BooleanField(default=False)
    first_comics = models.BooleanField(default=False)
    author = models.CharField(max_length=128)
    category = models.CharField(max_length=50, default='Other')
    hero = models.CharField(max_length=50, default='Other')
    posseded = models.BooleanField(default=False)
    want = models.BooleanField(default=False)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)



    def __str__(self):
        return f'{self.title}'

class SeriesComics(Comics):
    pass
class Characters(Comics):
    pass



class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title

templates/base.html
{% load static %}

<html>
    <head>
        <title>Ma Librairie</title>
        <link rel="stylesheet" href="{% static 'style.css'  %}" />

    </head>
    <body>
        <div class="navbar">
            {% if user.is_authenticated %}
            
                <p>Bonjour {{user}}</p>
                {% if perms.blog.add_photo %}
                    <a href="{% url 'photo_upload' %}">Upload a Photo</a>
                {% endif %}        
                    {% if user.profile_photo %}
                    <img class="avatar" src="{{ request.user.profile_photo.url }}">
                {% else %}
                <img class="avatar" src="{% static 'user/profil_default.jpg' %}">
                {% endif %}        
                <p><a href="{% url 'upload_profile_photo' %}">Changer la photo de profil</a></p>
                <a href="{% url 'logout' %}">Se déconnecter</a>
                <!-- <p><a href="{% url 'follow_users' %}">Suivre des utilisateurs</a></p> -->
                <p><a href="{% url 'profile' %}">Mon profil</a></p>
                <p><a href="{% url 'all_profile' %}">voir les autres utilisateurs</a></p>
                
            </div>
        {% else %}
            bienvenue, veuillez vous connectez
            <a href="{% url 'login' %}">Se connecter</a>
            {% endif %}
        <div class="main">
            
        </div>
        {% block content %}{% endblock content %}
      


    </body>
</html>